name: Docker-Publish

on:
  push:
    # Publish `release` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: onchain-data-api
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t thisisprince/$IMAGE_NAME:$IMAGE_TAG .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            docker push thisisprince/$IMAGE_NAME:$IMAGE_TAG
          fi